{{-- Report Header with Logo - For all reports --}}
<div class="report-header mb-6 pb-4 border-b-2" style="border-color: #1E3A5F;">
    <div class="flex items-center justify-between">
        <div class="flex items-center">
            <img src="{{ asset('images/logo/s2e-logo.svg') }}" alt="S2E Logistics" class="h-16 w-auto mr-4">
            <div>
                <h1 class="text-2xl font-bold" style="color: #FF6B35;">S2E LOGISTICS</h1>
                <p class="text-sm" style="color: #6B7280;">{{ $reportTitle ?? 'Report' }}</p>
            </div>
        </div>
        <div class="text-right">
            <p class="text-sm" style="color: #6B7280;">Date: {{ now()->format('Y-m-d') }}</p>
            <p class="text-sm" style="color: #6B7280;">Generated by: {{ Auth::user()->name ?? 'System' }}</p>
        </div>
    </div>
</div>

